import React from "react";
import './LaptopTable.css';
import './Home.css';


    
  function AsusLaptopsTable() {
    return (
      <div >
            <div className='lap'>
                  <h1>Best Asus Laptops on amazon</h1>
            </div>
            <div className="l-1">
               <h2>Gaming Laptops</h2>
            </div>
            <div className="home__row">
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07P13WFR5&asins=B07P13WFR5&linkId=7365e28ce817cfca180016cd320d9dad&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09C6C12TC&asins=B09C6C12TC&linkId=3e4cdf34cbf2c133aac03d245a8ecf7b&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B096KW953M&asins=B096KW953M&linkId=41c3ee27dd7edb3a7f78743caface079&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCMBHH1&asins=B09CCMBHH1&linkId=bf016b2b6bd4672d5c02ebd61b7ee683&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B096KX64T3&asins=B096KX64T3&linkId=ecf9e771627d5447fd75d115241ddd67&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCRBRW6&asins=B09CCRBRW6&linkId=1be1f85196ba2cb15a89be2275031c04&show_border=true&link_opens_in_new_window=true" />
                
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09LVMK3S9&asins=B09LVMK3S9&linkId=28af9a6e41178532a8a780684f457b80&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B095S9KD18&asins=B095S9KD18&linkId=8483f9a363f91e49cca6b3000c18007f&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B095SB6XKN&asins=B095SB6XKN&linkId=89fbb5ab5fd9515ddffc580ff32e67e7&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCT55R3&asins=B09CCT55R3&linkId=169614717f97fd279af5d27fd3a6a0e3&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCK8R2T&asins=B09CCK8R2T&linkId=e07c8f8a1a4537722df17e39c5f6fce2&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NYBL12G&asins=B09NYBL12G&linkId=94cb632ade028a932e23754c7cd361b8&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B096VHX239&asins=B096VHX239&linkId=66181bf38fc0214ae9366d9787941c18&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCQ453Z&asins=B09CCQ453Z&linkId=9c6f92fe8d6175c7ae6ce0279f712a55&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09LVKF4PR&asins=B09LVKF4PR&linkId=1e9c08d67f0c9cd42d906c586227f6fd&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCYXLD2&asins=B09CCYXLD2&linkId=6f7584f66c0a55748eae4a5f3cd0a72c&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCLPWKD&asins=B09CCLPWKD&linkId=d10efb602126d067838414041884c8d8&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CBZFPZR&asins=B09CBZFPZR&linkId=50d4f64fca91a60dbfc363be8df318f9&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCW5XVM&asins=B09CCW5XVM&linkId=10709be5829ddb574a73a7424d1a5f08&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B096VKNKSG&asins=B096VKNKSG&linkId=ba565495bce64baa66c6b3bd15d7c5af&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08CRMTKMK&asins=B08CRMTKMK&linkId=965b810f76c222c23fced235a9b12d52&show_border=true&link_opens_in_new_window=true" />
                <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/34Xbdgn"}}>View more</button>
               
             </div >
             <div className="l-1">
               <h2>Working Laptops</h2>
             </div>
             <div className="home__row" >
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08JXGXTC6&asins=B08JXGXTC6&linkId=4c77aa99ed19113df882523cf4bbbe82&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08P63QH9F&asins=B08P63QH9F&linkId=9c7762dd69851f04775c52f1f64fac79&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NHVS8DB&asins=B09NHVS8DB&linkId=7076b7d396717fc29d29306df0b74ae9&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08CGKFW23&asins=B08CGKFW23&linkId=582cf33f866db7980cb09e206d12eea7&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08CGSB5MX&asins=B08CGSB5MX&linkId=dbf5dbdf628cd6a73caa366648a2ef13&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B091CP32S3&asins=B091CP32S3&linkId=8c3a50e66e6e85dca5121e2bb1f7f673&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B095C6DBB3&asins=B095C6DBB3&linkId=962e214316dba4e92c10c895dc6c09df&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G9Y56X3&asins=B09G9Y56X3&linkId=4cd9491ece1e200de7e93d9f80894cb3&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G9Z5D3C&asins=B09G9Z5D3C&linkId=2256781d830ceba9b5c031dc5b02bba9&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08W9G8NBD&asins=B08W9G8NBD&linkId=f59d1fce258a555050467eff3531d54b&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B098F7RXYR&asins=B098F7RXYR&linkId=c6065dff8523173567106416dcee8b43&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08PQW6W1L&asins=B08PQW6W1L&linkId=634030d45a9d1b0f3c026023b55128a4&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08CKQS8VV&asins=B08CKQS8VV&linkId=1e7ff485116f48155f24b3fe240432a3&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09BF65Z1V&asins=B09BF65Z1V&linkId=05116bdbf1dedbf220b9052bd42f95d9&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08CDV49P2&asins=B08CDV49P2&linkId=a1a419de8da23cd2cd6f050e2fe3b4c6&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08D3T9CK3&asins=B08D3T9CK3&linkId=cdd5f463ddbd35205ea894f6a5737522&show_border=true&link_opens_in_new_window=true" />
                <iframe title="al" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CCQWC66&asins=B09CCQWC66&linkId=2b313d4508690724850393b6c58d809f&show_border=true&link_opens_in_new_window=true" />

                  
                  <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3sVQXDL"}}>View more</button>
             </div>
             
         
      </div>
    );
  }
    
  export default AsusLaptopsTable;