import React from "react";
import './LaptopTable.css';
import './Home.css';


    
  function DellLaptopsTable() {
    return (
      <div >
            <div className='lap'>
                  <h1>Best DELL Laptops on amazon</h1>
            </div>
                
        
            <div className="home__row">
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09F3PCD31&asins=B09F3PCD31&linkId=efeb81d59cac712a7120ac357068ce20&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08GYGRZZJ&asins=B08GYGRZZJ&linkId=9f8887fc062466594f4e3c1d5431b490&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09F3PCD31&asins=B09F3PCD31&linkId=efeb81d59cac712a7120ac357068ce20&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NLSMR4K&asins=B09NLSMR4K&linkId=71ecbb0863ecb905184a1f90d9ce202d&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09F3PY7K2&asins=B09F3PY7K2&linkId=6043070b47f099d94867ee5e65c29981&show_border=true&link_opens_in_new_window=true" />   
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08BZQMPFK&asins=B08BZQMPFK&linkId=a23ceb897130015ca689404c467e0c0b&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NLS9H3N&asins=B09NLS9H3N&linkId=48f86e452d1745ff52986ebbd9c083ef&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08QCKPLZX&asins=B08QCKPLZX&linkId=e8aaaf2808f4b60b65da1eb83e8ea06f&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NLSS2NG&asins=B09NLSS2NG&linkId=fcb384e64b6f4683e3a88a142808013a&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NLSSGQT&asins=B09NLSSGQT&linkId=d83381f60ae2aaa14cc3196ae3cf2340&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NLS8HWD&asins=B09NLS8HWD&linkId=e55f52914bdf037117b2a35a9e52a338&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09F5KMH9L&asins=B09F5KMH9L&linkId=7edf08f4902312312b2a2697a823ca0c&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NLSFZ9S&asins=B09NLSFZ9S&linkId=01017717598b075345ae95ac0241aa38&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09F3RF871&asins=B09F3RF871&linkId=be20c75334ae72fc7862baa06e81f79f&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08X4NF6M4&asins=B08X4NF6M4&linkId=5cae0ea3292f87a648ede1de416ee9d8&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B095S8HPMY&asins=B095S8HPMY&linkId=a04e188912a87692ea3d402544e00499&show_border=true&link_opens_in_new_window=true" />
                <iframe title="dl" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097C3B9DZ&asins=B097C3B9DZ&linkId=fca2852e62881b7f58e6b77e88264b88&show_border=true&link_opens_in_new_window=true" />
                
                <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3HMbNvn"}}>View more</button>
            </div>
            
         
      </div>
    );
  }
    

    
  export default DellLaptopsTable;