import React from "react";
import './LaptopTable.css';
import './Home.css';


    
  function HPLaptopsTable() {
    return (
      <div >
            <div className='lap'>
                  <h1>Best HP Laptops on amazon</h1>
            </div>
                
        
            <div className="home__row">
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B091FJ5WPQ&asins=B091FJ5WPQ&linkId=45e018bade416732226edd5713bfc527&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09H6R5J1H&asins=B09H6R5J1H&linkId=b56afb2bf21a44937fd3db8c93fe763a&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09J2GR7X3&asins=B09J2GR7X3&linkId=fbfb4a1df7b4724e5ec70a1c406751dc&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09LM6CYC4&asins=B09LM6CYC4&linkId=e7edc34a3387e9168ba55ba0d0b3ce08&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08VSYYPJ2&asins=B08VSYYPJ2&linkId=00e8ff95ca8ae752ae786b2927c8fb39&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08CGJ5K3V&asins=B08CGJ5K3V&linkId=af3ff09c64b0f0494b257441d13eb9c6&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09P2RT87H&asins=B09P2RT87H&linkId=96dd3c2a0420c7cfddd737b224b9c9b5&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08D5F4B6M&asins=B08D5F4B6M&linkId=300d4eca80494662809a997ad6225f17&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09MH5MLYP&asins=B09MH5MLYP&linkId=e97bf6000edc26324e84d6e3bfe63f15&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09PBTLW9F&asins=B09PBTLW9F&linkId=036ef3bbc417f1f8998439aa9a19f460&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09MH5MLYP&asins=B09MH5MLYP&linkId=f6a6bd53e109fb59121faf7590e71171&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09KGQGJ6K&asins=B09KGQGJ6K&linkId=b6aee8974aa6992359e8a10429669cbc&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B098393BRS&asins=B098393BRS&linkId=e34fd02b1b8fae65fd9c046d86b08b64&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09KM1BVFH&asins=B09KM1BVFH&linkId=791600eb5f7c001e46f9aa17bb3931e2&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08T6THSMQ&asins=B08T6THSMQ&linkId=360c37c71624c26432f193a982aea1ea&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08T6THSMQ&asins=B08T6THSMQ&linkId=360c37c71624c26432f193a982aea1ea&show_border=true&link_opens_in_new_window=true" />
               <iframe title="hl" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08C5W6PL2&asins=B08C5W6PL2&linkId=9cdcbd160590cb8eed9db310503b3c41&show_border=true&link_opens_in_new_window=true" />
               <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3GTaEkM"}}>View more</button>
            </div>
            
         
      </div>
    );
  }
    
export default HPLaptopsTable;