import React from "react";
import './LaptopTable.css';
import './Home.css';


    
  function LenovoLaptopsTable() {
    return (
      <div >
            <div className='lap'>
                  <h1>Best Lenovo Laptops on amazon</h1>
            </div>
                
        
            <div className="home__row">
                
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NP4W2PC&asins=B09NP4W2PC&linkId=26322aab0b2d82b291dae0281aed52a5&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09JBZ7JXD&asins=B09JBZ7JXD&linkId=caba9053307b11852087fd013a230061&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09DMYZW5Q&asins=B09DMYZW5Q&linkId=d54650c8734e72b206a5b6f1fc6d3246&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097TY6PTN&asins=B097TY6PTN&linkId=14bf6217dd29c70119ed2204f7f72460&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09M3ZKH1T&asins=B09M3ZKH1T&linkId=9b042819a415edf73306184285b6de76&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09DMKWNPR&asins=B09DMKWNPR&linkId=f89afe08df29849940227233482760d9&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B094XL5V92&asins=B094XL5V92&linkId=e512f64c1d200e8221828890a43a8625&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09GB2KYGC&asins=B09GB2KYGC&linkId=aac807ad44f8a57a928c6e0519088e24&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09M423NVT&asins=B09M423NVT&linkId=98f75faea437d7182ec0d63762ade6f3&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09NP5PCVY&asins=B09NP5PCVY&linkId=06a9c3cee21eff377671345ca177ca81&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G39QZZW&asins=B09G39QZZW&linkId=e5951668d4b78fa083a6a4ba58e67c2c&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09Q511LN5&asins=B09Q511LN5&linkId=24834876d3130d5f2bb037a02f50188b&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09DMGTJ1Q&asins=B09DMGTJ1Q&linkId=09426b5fb66446805a943ca0ee248624&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09MKNM92J&asins=B09MKNM92J&linkId=0792c60a4a217853cf2aa89d7090d294&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09K5TVP2B&asins=B09K5TVP2B&linkId=1dcf1d9554c69aff5eaf59bb1560f8a7&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09BVX13XW&asins=B09BVX13XW&linkId=3a9d7d1c7e56506c6a03761906f3ffd2&show_border=true&link_opens_in_new_window=true" />
                <iframe title="ll" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G9ZPV38&asins=B09G9ZPV38&linkId=cc76c12c59c8b147edc86cdbdc79fa95&show_border=true&link_opens_in_new_window=true" />
                <button title="ll" className="more_btn" onClick={() => {window.location.href="https://amzn.to/3H37vyJ"}}>View more</button>
            </div>
            
         
      </div>
    );
  }
    
  export default LenovoLaptopsTable;