import React from "react";
import './LaptopTable.css';
import './Home.css';


    
  function MobilesTop() {
    return (
      <div >
            <div className='lap'>
                  <h1>Best Mobiles on amazon</h1>
            </div>
                
        
            <div className="home__row">
      
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G8Y7BMX&asins=B09G8Y7BMX&linkId=bba6af3782a17078b740229e91b767d4&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CQ3GSJ1&asins=B09CQ3GSJ1&linkId=a87274acc16907c6e7724eab09a6e1ae&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08Z721V2R&asins=B08Z721V2R&linkId=4a7c51cd1212076f814163727e14d7e2&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CQ1Q544&asins=B09CQ1Q544&linkId=906e868d24cf8dc5dfd43fe69ff958fb&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G91FCBT&asins=B09G91FCBT&linkId=973c546ff0cf1ea23c0527ac6058fdde&show_border=true&link_opens_in_new_window=true" />
               
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08Z72BSJJ&asins=B08Z72BSJJ&linkId=cff22db45030ea2e94ba529a0d24ba5a&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G9DBNNN&asins=B09G9DBNNN&linkId=978855ae3a5fb8c3d92600f571b8e5f0&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08L5W2S3Q&asins=B08L5W2S3Q&linkId=60e8134f0efbee41e232f806d5ddbbb1&show_border=true&link_opens_in_new_window=true" />
                
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09SZRTNYD&asins=B09SZRTNYD&linkId=893a408d18e11dd3ffb2f160b174ba95&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08V8PR9WL&asins=B08V8PR9WL&linkId=f8c4da991a4e60b9d619baa2411ec162&show_border=true&link_opens_in_new_window=true" />
                
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G984RNC&asins=B09G984RNC&linkId=1745beab3e05c18a38998a93ff66974c&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CPZPY2N&asins=B09CPZPY2N&linkId=7274050abbd2ad6e5c687afab857d324&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G9HDN4Q&asins=B09G9HDN4Q&linkId=77edfc58979d90424f9a34c660d2cbc0&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G9D8KRQ&asins=B09G9D8KRQ&linkId=e40a65d762b5b716cc36ea682936d866&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09JP5NCMP&asins=B09JP5NCMP&linkId=7b0685cdd54ed6d0be285199cd98635c&show_border=true&link_opens_in_new_window=true" />
               
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B089MVKH71&asins=B089MVKH71&linkId=50a784dbc661e647d38deb1b97d09433&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B089MS7D9K&asins=B089MS7D9K&linkId=15c6ab8337e64f2d1487dda5c49e4460&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08697MJFD&asins=B08697MJFD&linkId=dbe0530bb95fa2123647c9a1ce32709b&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09DCHV874&asins=B09DCHV874&linkId=2a275a90848a7f7d85ec51d410089479&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B096FQMQFC&asins=B096FQMQFC&linkId=2fe656ba938cc6a683320c6e7c27603a&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097RDVDL2&asins=B097RDVDL2&linkId=af46c1a94040131d534af84083519a39&show_border=true&link_opens_in_new_window=true" />
               
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09CV463ZY&asins=B09CV463ZY&linkId=47dd951f4e153a8b87c767a52eb1f5e7&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G39YXFS&asins=B09G39YXFS&linkId=6792f328272f2fe5d1a484a2780ae7f7&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09G3CSL7Y&asins=B09G3CSL7Y&linkId=a5a76138408c04d1609f02e6cb39c00f&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07WGPJV3H&asins=B07WGPJV3H&linkId=77c3479137ce3afd47741320f583e03c&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07WHR5RKH&asins=B07WHR5RKH&linkId=097e3e1b8b87ce891bd93ebd3e5ea5a7&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08444S68L&asins=B08444S68L&linkId=6fd6fbfeec58268a328adcaccb7148ee&show_border=true&link_opens_in_new_window=true" />
                <iframe title="m" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08444S68L&asins=B08444S68L&linkId=6fd6fbfeec58268a328adcaccb7148ee&show_border=true&link_opens_in_new_window=true" />




                <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3BWDMq9"}}>View more</button>
            </div>
            
         
      </div>
    );
  }
    
  export default MobilesTop;