import React from "react";
import './LaptopTable.css';
import './Home.css';


    
  function SonyTV() {
    return (
      <div >
            <div className='lap'>
                  <h2>SONY Smart TV'S</h2>
            </div>
                
        
            <div className="home__row">
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097BFSP6X&asins=B097BFSP6X&linkId=c4aaabc42599b3766148ef1f42710782&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097C2XVK8&asins=B097C2XVK8&linkId=45934bd7d9c81114dd73c8672ab2a354&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B095MG6V5Z&asins=B095MG6V5Z&linkId=e5d68c5a08c00bcf8e95b4f48f085d98&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097C1GLJK&asins=B097C1GLJK&linkId=fa6b38a41d055f4b8c33674102632306&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0943PRP37&asins=B0943PRP37&linkId=5ee92608f6c31373393c7c5cb54b7240&show_border=true&link_opens_in_new_window=true" />

                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08FTX6SYD&asins=B08FTX6SYD&linkId=f2c4cea2047c6a80e50497d6d6343e71&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097C1GLJK&asins=B097C1GLJK&linkId=9b7c644bd86b9d4a08eef593fb4bea46&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097C137Y3&asins=B097C137Y3&linkId=983ad758372e7f4646e8c741363854e0&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0943RMM18&asins=B0943RMM18&linkId=7e791b4d1bf163d3e67fb2ecf6e94730&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B091N3MQ92&asins=B091N3MQ92&linkId=e6a0b332a5925ecb6b108b2927d57bcd&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0918R8PZ5&asins=B0918R8PZ5&linkId=f8c595024ae7201676459e125cd41da0&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0918T1SDK&asins=B0918T1SDK&linkId=4c68b24b61aeab29014a16776aeec1b3&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097C1VVKK&asins=B097C1VVKK&linkId=ff09ddf3d403227418bf21b0086b4c39&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B091MKSN5R&asins=B091MKSN5R&linkId=757a321a513b4b1b5cabeb7c3db12316&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B095MDPDT2&asins=B095MDPDT2&linkId=15146c6d5ad56cc45ac24f01bb57ff02&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0918T1SDK&asins=B0918T1SDK&linkId=f669073dd2cda048983bd57a35dfd5bb&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B094XHXJ5W&asins=B094XHXJ5W&linkId=477a59a20bc2438c344b5c1cae682609&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07TVMDNXD&asins=B07TVMDNXD&linkId=18d4b80376420b0048dae023b5b24cd3&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B084T8LVPV&asins=B084T8LVPV&linkId=92fbf9b83aa630e05ac3d82e60db66c6&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07QC6YQ3L&asins=B07QC6YQ3L&linkId=b74e098051c872297eb56b42e18f68b5&show_border=true&link_opens_in_new_window=true" />

                
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B086CGNG4T&asins=B086CGNG4T&linkId=8a9e3477575f4890ca43e806742c512f&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08ZJYBMPM&asins=B08ZJYBMPM&linkId=f61c5656b0d3d6c4744e8e2ab8a0d8c6&show_border=true&link_opens_in_new_window=true" />
                <iframe title="st" className='products' style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B084T8MD6P&asins=B084T8MD6P&linkId=80a3127f12aadf5ee77a0e5a04a53663&show_border=true&link_opens_in_new_window=true" />
                <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3IfQ0wm"}}>View more</button>
            </div>
            
         
      </div>
    );
  }
    
  export default SonyTV;