import React from "react";
import './Header.css';
import './Watches.css';

import './Laptops.css';
import './Home.css';
import Header from './Header';
import Navlinks from './Navlinks';
import Footer from './Footer';
import CarouselWatches from "./CarouselWatches";



function Watches(){
    return(
        <div className='watches'>
            <Header/>
            <Navlinks/>
            <div className='lap'>
                <h1>Watches</h1>
            </div>
             <div>
                 <CarouselWatches/>
             </div>
          
            <div className="lap"> 
                <h1>Best Watches on amazon</h1>
            </div>
            <div className="home__row">
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07T3SJXNX&asins=B07T3SJXNX&linkId=1392c4a82f05fbaa760ca728ce665656&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B072LG89PQ&asins=B072LG89PQ&linkId=31a9b320533dc300b97cffae9cd997c0&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07QG3Z9N2&asins=B07QG3Z9N2&linkId=6a1f7baecf052ead1cd3482ac3f331ec&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07ZGNPFNK&asins=B07ZGNPFNK&linkId=6bc08ac92d4207a97d87c6b7830deade&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07QLVHBLF&asins=B07QLVHBLF&linkId=855e0cb1796c7871c8ab2b582e8b0669&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09DGS966L&asins=B09DGS966L&linkId=fe9cd094cfd13961c43b2b5ace50a982&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08FS835KH&asins=B08FS835KH&linkId=a429f40b776e562b960fde2463327eb4&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09DG9VNWB&asins=B09DG9VNWB&linkId=6404d00376d402163c10de5c6c0844ad&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09DG7RZHC&asins=B09DG7RZHC&linkId=d6f6a023491edc0d7775b7e5a26feb85&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B092CR3TJ3&asins=B092CR3TJ3&linkId=8ccca70722126b4806c0e9205f5f4152&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08F79FND9&asins=B08F79FND9&linkId=233fc53b654478d9cc2af435a656509e&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07SRVV8V4&asins=B07SRVV8V4&linkId=26320809e9e378d6147cdc259c1c8d29&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08DFPV5Y2&asins=B08DFPV5Y2&linkId=1110af5404c633ea43413b90b3270e72&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08FWKGKC2&asins=B08FWKGKC2&linkId=4a332e06aba14285b77362e9d72f2757&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09HVCFLG4&asins=B09HVCFLG4&linkId=dd66a7a669a01bb66195cc75e50d58fa&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08XWRSKVK&asins=B08XWRSKVK&linkId=6dae2a84ef7a8dbd9e538c32f6a217a8&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08PWM5GCG&asins=B08PWM5GCG&linkId=be191b5292a1d3d3936c4e81952fa58b&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B094NDJBZN&asins=B094NDJBZN&linkId=7d1e8dba4ace278ff1ff119b31d05e77&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08SDLLPSW&asins=B08SDLLPSW&linkId=1190d50e8b2ce5cc1aec150386b8d89d&show_border=true&link_opens_in_new_window=true" />
              <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07TWFVDWT&asins=B07TWFVDWT&linkId=bfa13a42581cfcc44078385b8e78c81c&show_border=true&link_opens_in_new_window=true" />
              <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/35wprVo"}}>View more</button>

            </div>
            <div className="lap"> 
                <h2>Smart Watches Having Calling Feature </h2>
            </div>
            <div className="home__row">
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0972BQ2RS&asins=B0972BQ2RS&linkId=157f884be1e3eeeb950cdb280262d99d&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09RFHZ91M&asins=B09RFHZ91M&linkId=12e2506707670fbd5ab89a309f8d93f2&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09KS1RNWS&asins=B09KS1RNWS&linkId=33caecb2eee889749765d2ac7c1a7c6f&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08QTNNTQ9&asins=B08QTNNTQ9&linkId=18c2d3afc72e68b3f52b67dfd4152f1d&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09GFRF1BX&asins=B09GFRF1BX&linkId=962d85ce7095490fa7f8f7a70e9a12e8&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09F6QF2M2&asins=B09F6QF2M2&linkId=f1ff1cec6eb09fb7369f6389720c5344&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09F6QNRSP&asins=B09F6QNRSP&linkId=a4532190cda5f510bfb0de35ad9d1e9d&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09FFFS78C&asins=B09FFFS78C&linkId=61c5c5d94a92c3bf65ee51e5df9c1a6c&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09N3NZHV7&asins=B09N3NZHV7&linkId=14e20cc63822b5b3f457b6678c91a8b9&show_border=true&link_opens_in_new_window=true" />
            <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B097XMXHXB&asins=B097XMXHXB&linkId=9d9d9e8add5c66890a3fd500747f7024&show_border=true&link_opens_in_new_window=true" />
            <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3HcbUPS"}}>View more</button>
            
            </div>
           
       
            
            <div className="lap">
                <h1>Best Watches for Women</h1>
            </div>
            <div className="l-1">
                <h2>Fossil watches</h2>
            </div>
            <div className="home__row">
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08FWRPDZY&asins=B08FWRPDZY&linkId=481122315003d61ba85cbb9456c3cfab&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B084CFV5V6&asins=B084CFV5V6&linkId=2c4a4c46c81b5a992463585533b5a561&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08QVDGPBS&asins=B08QVDGPBS&linkId=bf0c12c6ad2d34f0b5110b0beaad0508&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08HSY2JNT&asins=B08HSY2JNT&linkId=c19de959a31884d1c73432ea5e944602&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B00HG08KX6&asins=B00HG08KX6&linkId=54c7b4732bbbe6a309536311dbeb421a&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B075QBTBZS&asins=B075QBTBZS&linkId=1a6d117329778512a3e2ac3e7bc55207&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B077SN2R5P&asins=B077SN2R5P&linkId=e108e284b36152229f18630c9bb183c2&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0185TW0KU&asins=B0185TW0KU&linkId=e028c1264bdd0c7effcbca0f561e7d96&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B078XY2KLG&asins=B078XY2KLG&linkId=ce838fb9802e7b0018098687b88ddf09&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B00BPJHJYK&asins=B00BPJHJYK&linkId=f5ef7232a98c8d1fbca967384274a579&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B081VK6Q6V&asins=B081VK6Q6V&linkId=c3781af46b406f4eff9e9c8bc22fc503&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B01760QWY4&asins=B01760QWY4&linkId=f99c5f3db12258f067b2c14c89c3c828&show_border=true&link_opens_in_new_window=true" />
                 
                    <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3vqFa3k"}}>View more</button>
            
            </div>
            <div className="l-1">
                <h2>Titan watches</h2>
            </div>
            <div className="home__row">
                 
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07RK27GLQ&asins=B07RK27GLQ&linkId=3fe67567742933141b8851bd0dd01c24&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07X3TRBJQ&asins=B07X3TRBJQ&linkId=28816c9a3250849b0b0c020756013fdf&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07YLV9SDD&asins=B07YLV9SDD&linkId=fd311a4ae93f2d72d40ef7eb71b17b47&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07RM84125&asins=B07RM84125&linkId=9783df7166caf42ff87f3e7c2364f6e7&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07YLVHRXG&asins=B07YLVHRXG&linkId=6a69fbae20a888e1f700e01a4680b533&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07YLV4Q5D&asins=B07YLV4Q5D&linkId=06a0e693a5b849d1de063500718e2908&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08Q7NBS9K&asins=B08Q7NBS9K&linkId=099197a16e18cea292f9ce466274d2fd&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w"  className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B06X3VCVFM&asins=B06X3VCVFM&linkId=770e0ba392f365748836c5127c990c1e&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07YLVGJFW&asins=B07YLVGJFW&linkId=99173a4a7949f8f7dff80d90d4aa6f11&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B01N8UHNQD&asins=B01N8UHNQD&linkId=41e7a0ce6aec03b5aca0e2f38ad3e9b4&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07YLTTFNK&asins=B07YLTTFNK&linkId=21b7523b0d0cd2ced9bd337b84fcb7fc&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B01HB5SUK8&asins=B01HB5SUK8&linkId=58284cd4f74196028763669023f4ae79&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08HCVY1FG&asins=B08HCVY1FG&linkId=b2fcdfee47874cc507f149cd1fdd48ae&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B074PTYL5J&asins=B074PTYL5J&linkId=f3c42dc26fe3d23abded922f8543e12e&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07PN2V5DP&asins=B07PN2V5DP&linkId=214388bbad598c71e770b445ec2f4c6d&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07D2HY612&asins=B07D2HY612&linkId=6cfccf86f5680d5e7275408f2df430ac&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07D2F8JPG&asins=B07D2F8JPG&linkId=aa541edb4a14cb7008d5e0f57ec64009&show_border=true&link_opens_in_new_window=true" />
                 


                 <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3hn1e6y"}}>View more</button>
            </div>
            <div className="l-1">
                <h2>Garmin Smart watches</h2>
            </div>
            <div className="home__row">
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07QG3Z9N2&asins=B07QG3Z9N2&linkId=bf78e7d0f480d97b534d2de126ed19da&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08RMG4DH1&asins=B08RMG4DH1&linkId=ac871128c998a0394a71fbfcd9e4c525&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08N18JGRW&asins=B08N18JGRW&linkId=d1c0c622ecf42e4a98c3ca61d7cd5272&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08RM6QP7Q&asins=B08RM6QP7Q&linkId=72218385c4765a7f6ec5a47f9eb24f62&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08N19B4L1&asins=B08N19B4L1&linkId=9df11c624937162f53412791aa673cf2&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08N19B4L1&asins=B08N19B4L1&linkId=3795b2f28211b12307196b5fc9735f57&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08N4H7FVS&asins=B08N4H7FVS&linkId=40b7fb6e6f1423d9d6640b71ce4901ff&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B09M8TT6DZ&asins=B09M8TT6DZ&linkId=de29aa214d9ace7c3b104c7547514c66&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B08ZCTWL9C&asins=B08ZCTWL9C&linkId=974daff3b2c83ea5dbf9ad43b57c6799&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B094ZJB9JS&asins=B094ZJB9JS&linkId=dc92284f7317405876cc4743b4058e83&show_border=true&link_opens_in_new_window=true" />
                <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B0972BQ2RS&asins=B0972BQ2RS&linkId=aa9a12dda50aeb86746de979933dd0c4&show_border=true&link_opens_in_new_window=true" />
                
                 
                 

                 <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/3C0fADh"}}>View more</button>
            </div>
            <div className="l-1">
                <h2>Daniel klein Watches</h2>
            </div>
            <div className="home__row">
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B011PLQD12&asins=B011PLQD12&linkId=1f0c454098712c8d6125b892bcaba240&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B011PLQD12&asins=B011PLQD12&linkId=1f0c454098712c8d6125b892bcaba240&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B076K8VR7R&asins=B076K8VR7R&linkId=f0fb4ced3b4d9720e6dc155eac7fc17e&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07V56K6LS&asins=B07V56K6LS&linkId=0ba1fcc6d43fd288a408d4e5d9f89874&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07B6KWYL4&asins=B07B6KWYL4&linkId=9d985e76cef50820bebda85f8bf61d36&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07V7D9N2V&asins=B07V7D9N2V&linkId=9f068f6ce9fecb971ea816cc0b8d5d01&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B01MT7PDX4&asins=B01MT7PDX4&linkId=6a5b62406e74b54d34530507d37992fa&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07V9X8F7M&asins=B07V9X8F7M&linkId=5da1da4fe99a80ed90b93c3aad9c6b65&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07V8HL8Y8&asins=B07V8HL8Y8&linkId=134065b3668352a7bf8ec4c36922de8c&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07SFQZQ1T&asins=B07SFQZQ1T&linkId=d983561bdd3fc3a9be94960ccf3b3966&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B081B8YT5N&asins=B081B8YT5N&linkId=57920aed6ddcb1f49f8108fc8da2d841&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07B6JD5ZH&asins=B07B6JD5ZH&linkId=eb79fcd107d5b69bc3358a9d114ff785&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07CTQXMSW&asins=B07CTQXMSW&linkId=6c7ce012f2bb6160e37f2b4d4bce1dff&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07B6JD5ZH&asins=B07B6JD5ZH&linkId=a53f91b412460b16f97cb99f24124250&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07NVMQ5PH&asins=B07NVMQ5PH&linkId=e83fc0d2d8bf7b5c4446448882f8c69e&show_border=true&link_opens_in_new_window=true" />
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07TSJ4WWR&asins=B07TSJ4WWR&linkId=bd17720766c65c7c274552e709330af9&show_border=true&link_opens_in_new_window=true" />
                 
                 <iframe title="w" className="products" style={{width: '120px', height: '240px'}} marginWidth={0} marginHeight={0} scrolling="no" frameBorder={0} src="//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=sahara059-21&language=en_IN&marketplace=amazon&region=IN&placement=B07FCPL5NX&asins=B07FCPL5NX&linkId=d83d8cd05f7f38aead69887de2af8c5a&show_border=true&link_opens_in_new_window=true" />
                 
                 

                 <button className="more_btn" onClick={() => {window.location.href="https://amzn.to/33Y9iHQ"}}>View more</button>
            </div>
             
            
            <Footer/>
            
            
               
        </div>
    );
}
export default Watches;